github:
  api_key: <API_KEY>
  organization_name: example-org
  project_no: 1
  bucket_param_name: Status

tracked_actions:
  - opened
  - edited
  - deleted
  - closed
  - reopened
  - assigned
  - unassigned
  - labeled
  - unlabled
tracked_labels:
  - 동기화됨
